AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end
  
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/FirstHashElementIndentation:
  Enabled: false
  
Layout/HashAlignment:
  Enabled: true
  EnforcedLastArgumentHashStyle: always_ignore
  
Layout/LineLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
  
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true
  EnforcedStyle: indent

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/ClassLength:
  Max: 100

Metrics/ModuleLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - spec/**/*_spec.rb
    
Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    inject: 'inject'
    
Style/Documentation:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
  SupportedStyles:
    - always

Style/HashEachMethods:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Style/SignalException:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/TrivialAccessors:
  AllowPredicates: true
  
Style/WordArray:
  Enabled: false
